{"errorMessage": "name 'datetime' is not defined", "errorType": "NameError", "requestId": "878acc01-495a-4c44-8ffb-37aa6dba5396", "stackTrace": ["  File \"/var/task/lambda_function.py\", line 24, in handler\n    data = transform_data(data)\n", "  File \"/var/task/lambda_function.py\", line 11, in transform_data\n    record[\"transactiondatetime\"] = datetime.strptime(\n"]}